USE [master]
GO

DECLARE @dbname nvarchar(128)
SET @dbname = N'CoreBB'

IF (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE ('[' + name + ']' = @dbname OR name = @dbname)))
	DROP DATABASE [CoreBB]

CREATE DATABASE [CoreBB]
GO
ALTER DATABASE [CoreBB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoreBB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CoreBB] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [CoreBB] SET ANSI_NULLS ON 
GO
ALTER DATABASE [CoreBB] SET ANSI_PADDING ON 
GO
ALTER DATABASE [CoreBB] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [CoreBB] SET ARITHABORT ON 
GO
ALTER DATABASE [CoreBB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CoreBB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CoreBB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CoreBB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CoreBB] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [CoreBB] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [CoreBB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CoreBB] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [CoreBB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CoreBB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CoreBB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CoreBB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CoreBB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CoreBB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CoreBB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CoreBB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CoreBB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CoreBB] SET RECOVERY FULL 
GO
ALTER DATABASE [CoreBB] SET  MULTI_USER 
GO
ALTER DATABASE [CoreBB] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [CoreBB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CoreBB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CoreBB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CoreBB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CoreBB', N'ON'
GO
ALTER DATABASE [CoreBB] SET QUERY_STORE = OFF
GO
USE [CoreBB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [CoreBB]
GO
/****** Object:  Table [dbo].[Forum]    Script Date: 12/16/2017 3:12:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Forum](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OwnerID] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](1000) NULL,
	[CreateDateTime] [datetime2](7) NOT NULL,
	[IsLocked] [bit] NOT NULL,
 CONSTRAINT [PK_Forum] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Message]    Script Date: 12/16/2017 3:12:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Message](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FromUserID] [int] NOT NULL,
	[ToUserID] [int] NOT NULL,
	[SendDateTime] [datetime2](7) NOT NULL,
	[IsRead] [bit] NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[Content] [nvarchar](1000) NOT NULL,
 CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Topic]    Script Date: 12/16/2017 3:12:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Topic](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OwnerID] [int] NOT NULL,
	[ForumID] [int] NOT NULL,
	[RootTopicID] [int] NULL,
	[ReplyToTopicID] [int] NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Content] [nvarchar](1000) NOT NULL,
	[PostDateTime] [datetime2](7) NOT NULL,
	[ModifiedByUserID] [int] NULL,
	[ModifyDateTime] [datetime2](7) NULL,
	[IsLocked] [bit] NOT NULL,
 CONSTRAINT [PK_Topic] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 12/16/2017 3:12:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](1000) NULL,
	[IsAdministrator] [bit] NOT NULL,
	[IsLocked] [bit] NOT NULL,
	[RegisterDateTime] [datetime2](7) NOT NULL,
	[LastLogInDateTime] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Forum]  WITH CHECK ADD  CONSTRAINT [FK_Forum_Owner] FOREIGN KEY([OwnerID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Forum] CHECK CONSTRAINT [FK_Forum_Owner]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_FromUser] FOREIGN KEY([FromUserID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_FromUser]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_ToUser] FOREIGN KEY([ToUserID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_ToUser]
GO
ALTER TABLE [dbo].[Topic]  WITH CHECK ADD  CONSTRAINT [FK_Topic_Forum] FOREIGN KEY([ForumID])
REFERENCES [dbo].[Forum] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Topic] CHECK CONSTRAINT [FK_Topic_Forum]
GO
ALTER TABLE [dbo].[Topic]  WITH CHECK ADD  CONSTRAINT [FK_Topic_ModifiedByUser] FOREIGN KEY([ModifiedByUserID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Topic] CHECK CONSTRAINT [FK_Topic_ModifiedByUser]
GO
ALTER TABLE [dbo].[Topic]  WITH CHECK ADD  CONSTRAINT [FK_Topic_Owner] FOREIGN KEY([OwnerID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Topic] CHECK CONSTRAINT [FK_Topic_Owner]
GO
ALTER TABLE [dbo].[Topic]  WITH CHECK ADD  CONSTRAINT [FK_Topic_ReplyToTopic] FOREIGN KEY([ReplyToTopicID])
REFERENCES [dbo].[Topic] ([ID])
GO
ALTER TABLE [dbo].[Topic] CHECK CONSTRAINT [FK_Topic_ReplyToTopic]
GO
ALTER TABLE [dbo].[Topic]  WITH CHECK ADD  CONSTRAINT [FK_Topic_RootTopic] FOREIGN KEY([RootTopicID])
REFERENCES [dbo].[Topic] ([ID])
GO
ALTER TABLE [dbo].[Topic] CHECK CONSTRAINT [FK_Topic_RootTopic]
GO
USE [master]
GO
ALTER DATABASE [CoreBB] SET  READ_WRITE 
GO
